name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build with Grunt
      run: grunt

    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: akshnz/heroku-deploy@v3.0.0
      with:
        api-key: ${{ secrets.HEROKU_API_KEY }}
        app-name: ${{ secrets.HEROKU_APP_NAME }}
